name: ci-test

on:
  push:
    branches:
      - test-ci
  pull_request:
    branches:
      - test-ci

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: contains(github.event.head_commit.message, 'chore(versions)') == false
    strategy:
      matrix:
        node_version: [16.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - run: yarn -v
      - run: yarn --ignore-engines
      - name: ESlint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: '.'
      - run: |
          yarn build
          ls -l packages/components 

          
  


